### ISSUE TITLE
Use NS token for authentication of the NS viewer, if token is entered in settings

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#100]
It would be nice if when an access token is entered in the settings, this would also be used for authentication of the NS viewer in Loop Follow. 

When NS is authenticated using an access token, NS will show the name of the token for careportal entries. This makes it easier to know who is doing what when multiple caregivers (parents, school) are making entries. 

![image](https://user-images.githubusercontent.com/63544115/95510486-4a4a1900-09b6-11eb-8443-635027431caf.png)

If NS is authenticated with the API secret, the entry is "Entered by: undefined"

![image](https://user-images.githubusercontent.com/63544115/95510420-28509680-09b6-11eb-8530-ebdfc30c0270.png)

Since it is already possible to enter an access token in Loop Follow, it should also be used for NS authentication.

It would then be up to the user to select a token with careportal write privileges (role) if that is required.

Access token url example:
https://xxxxx.herokuapp.com/?token=name-zxczxczxc354345zcx

**Comment by jonfawcett** [comment]
Good catch. This was an oversight that I’ll get added

**Comment by jonfawcett** [comment]
Please test this in Dev and let me know if it works for you. I don't use tokens so cannot test fully. It is included in commit a136d3f31ba5e1792806ad8b46bfe173aa92995f

Also, I've been working on a build helper script that you can test if you'd like that simplifies updating and building. Just open terminal, paste the below, and hit enter. When it's done running, Xcode will be open and you just will need to sign and click play.

`/bin/bash -c "$(curl -fsSL https://git.io/JTKEt)"`

**Comment by bjornoleh** [comment]
Thanks, I can confirm that tokens are working now.

The cloning script is nice too!

**Comment by jonfawcett** [comment]
That’s fire testing. I merged it into dev and master
