### ISSUE TITLE
Signing for "LoopFollow" requires a development team 

### ISSUE THREAD

**Issue by paddingtonil** [jonfawcett/LoopFollow#108]
Getting build fail with following Signing for "LoopFollow" requires a development team. Select a development team in the Signing & Capabilities editor. I don't gave issues while building loop. 
iphone 11 ios 14.1
xcode 12.1

**Comment by jonfawcett** [comment]
Please send a screenshot of the full code window while on the signing screen

**Comment by paddingtonil** [comment]
![loop follow ](https://user-images.githubusercontent.com/54187576/98402650-5803c480-2070-11eb-8ce6-ae2d4d58e403.png)

**Comment by jonfawcett** [comment]
You have the project file open instead of the workspace file.
