### ISSUE TITLE
No such module 'Eureka'

### ISSUE THREAD

**Issue by FionnCole12** [jonfawcett/LoopFollow#111]
Hi John, I've updated my macbook air to Big Sur and I've cloned the dev branch to see if I can compile Loop follow with the updates to the operating systems. When I try to run the project I'm getting a buildtime error which starts by saying No Such module 'Eureka'.

import UIKit
import Eureka

class AlarmViewController: FormViewController {
    var appStateController: AppStateController?
    
    var soundFiles: [String] = [
        "Alarm_Buzzer",
        "Alarm_Clock",
        "Alert_Tone_Busy",
        "Alert_Tone_Ringtone_1",
        "Alert_Tone_Ringtone_2",
        "Alien_Siren",
        "Ambulance",
        "Analog_Watch_Alarm",
        "Big_Clock_Ticking",
        "Burglar_Alarm_Siren_1",
        "Burglar_Alarm_Siren_2",
        "Cartoon_Ascend_Climb_Sneaky",
        "Cartoon_Ascend_Then_Descend",
        "Cartoon_Bounce_To_Ceiling",
        "Cartoon_Dreamy_Glissando_Harp",
        "Cartoon_Fail_Strings_Trumpet",
        "Cartoon_Machine_Clumsy_Loop",
        "Cartoon_Siren",
        "Cartoon_Tip_Toe_Sneaky_Walk",
        "Cartoon_Uh_Oh",
        "Cartoon_Villain_Horns",
        "Cell_Phone_Ring_Tone",
        "Chimes_Glassy",
        "Computer_Magic",
        "CSFX-2_Alarm",
        "Cuckoo_Clock",
        "Dhol_Shuffleloop",
        "Discreet",
        "Early_Sunrise",
        "Emergency_Alarm_Carbon_Monoxide",
        "Emergency_Alarm_Siren",
        "Emergency_Alarm",
        "Ending_Reached",
        "Fly",
        "Ghost_Hover",
        "Good_Morning",
        "Hell_Yeah_Somewhat_Calmer",
        "In_A_Hurry",
        "Indeed",
        "Insistently",
        "Jingle_All_The_Way",
        "Laser_Shoot",
        "Machine_Charge",
        "Magical_Twinkle",
        "Marching_Heavy_Footed_Fat_Elephants",
        "Marimba_Descend",
        "Marimba_Flutter_or_Shake",
        "Martian_Gun",
        "Martian_Scanner",
        "Metallic",
        "Nightguard",
        "Not_Kiddin",
        "Open_Your_Eyes_And_See",
        "Orchestral_Horns",
        "Oringz",
        "Pager_Beeps",
        "Remembers_Me_Of_Asia",
        "Rise_And_Shine",
        "Rush",
        "Sci-Fi_Air_Raid_Alarm",
        "Sci-Fi_Alarm_Loop_1",
        "Sci-Fi_Alarm_Loop_2",
        "Sci-Fi_Alarm_Loop_3",
        "Sci-Fi_Alarm_Loop_4",
        "Sci-Fi_Alarm",
        "Sci-Fi_Computer_Console_Alarm",
        "Sci-Fi_Console_Alarm",
        "Sci-Fi_Eerie_Alarm",
        "Sci-Fi_Engine_Shut_Down",
        "Sci-Fi_Incoming_Message_Alert",
        "Sci-Fi_Spaceship_Message",
        "Sci-Fi_Spaceship_Warm_Up",
        "Sci-Fi_Warning",
        "Signature_Corporate",
        "Siri_Alert_Calibration_Needed",
        "Siri_Alert_Device_Muted",
        "Siri_Alert_Glucose_Dropping_Fast",
        "Siri_Alert_Glucose_Rising_Fast",
        "Siri_Alert_High_Glucose",
        "Siri_Alert_Low_Glucose",
        "Siri_Alert_Missed_Readings",
        "Siri_Alert_Transmitter_Battery_Low",
        "Siri_Alert_Urgent_High_Glucose",
        "Siri_Alert_Urgent_Low_Glucose",
        "Siri_Calibration_Needed",
        "Siri_Device_Muted",
        "Siri_Glucose_Dropping_Fast",
        "Siri_Glucose_Rising_Fast",
        "Siri_High_Glucose",
        "Siri_Low_Glucose",
        "Siri_Missed_Readings",
        "Siri_Transmitter_Battery_Low",
        "Siri_Urgent_High_Glucose",
        "Siri_Urgent_Low_Glucose",
        "Soft_Marimba_Pad_Positive",
        "Soft_Warm_Airy_Optimistic",
        "Soft_Warm_Airy_Reassuring",
        "Store_Door_Chime",
        "Sunny",
        "Thunder_Sound_FX",
        "Time_Has_Come",
        "Tornado_Siren",
        "Two_Turtle_Doves",
        "Unpaved",
        "Wake_Up_Will_You",
        "Win_Gain",
        "Wrong_Answer"
    ]
    
    func reloadSnoozeTime(key: String, setNil: Bool, value: Date = Date()) {
        
            if let row = form.rowBy(tag: key) as? DateTimeInlineRow {
                if setNil {
                    row.value = nil
                } else {
                   row.value = value
                }
                
                row.reload()
            }
               
    }
    
    func reloadIsSnoozed(key: String, value: Bool) {
        
            if let row = form.rowBy(tag: key) as? SwitchRow {
            row.value = value
            row.reload()
            }
    }

**Comment by jonfawcett** [comment]
Open the workspace file, not the project file

**Comment by FionnCole12** [comment]
Hi,

many thanks I tried that (double clicking on workspace in the dev folder on my desktop). The compiler worked better but then stopped with the at the following point

      return (false, 0 )
    }
    
    func findNextCarbTime(timeWithin: Int, needle: TimeInterval, haystack: [carbGraphStruct], startingIndex: Int) -> Bool {
        
        if startingIndex > haystack.count - 2 { return false }
        if haystack[startingIndex + 1].date -  needle < Double(timeWithin) {
            return true
        }

        return false
    }
    
    func findNextBolusTime(timeWithin: Int, needle: TimeInterval, haystack: [bolusGraphStruct], startingIndex: Int) -> Bool {
        
        var last = false
        var next = true
        if startingIndex > haystack.count - 2 { return false }
        if startingIndex == 0 { return false }
        
        // Nothing to right that requires shift
        if haystack[startingIndex + 1].date -  needle > Double(timeWithin) {
            return false
        } else {
            // Nothing to left preventing shift
            if needle - haystack[startingIndex - 1].date > Double(timeWithin) {
                return true
            }
        }
        
        return false
    }

**Comment by FionnCole12** [comment]
Thanks, I did this but received the following message after the build moved on



![548F1042-00A4-4ABB-8B66-87B2CB60B8CC_1_105_c](https://user-images.githubusercontent.com/24882996/99181602-63698680-2727-11eb-815c-ba8804aea835.jpeg)
