### ISSUE TITLE
Glitch appearing when compiling Dev in Big Sur 

### ISSUE THREAD

**Issue by FionnCole12** [jonfawcett/LoopFollow#112]
Hi,

many thanks I tried that (double clicking on workspace in the dev folder on my desktop). The compiler worked better but then stopped with the at the following point
![548F1042-00A4-4ABB-8B66-87B2CB60B8CC_1_105_c](https://user-images.githubusercontent.com/24882996/99181639-ae839980-2727-11eb-981d-e917f032d7fd.jpeg)

_Originally posted by @FionnCole12 in https://github.com/jonfawcett/LoopFollow/issues/111#issuecomment-727529830_

**Comment by jonfawcett** [comment]
This was caused by Xcode 12.2 and I had the fix in Dev but I forgot to push it to Main branch after Xcode was released a few days ago. I just ensured Main and Dev both have the fix. So download the code again and you'll be good to go!

**Comment by FionnCole12** [comment]
Thanks very much J, I will give it a go.
