### ISSUE TITLE
No carb entries

### ISSUE THREAD

**Issue by rafaelsky** [jonfawcett/LoopFollow#115]
Hi. In the loop follow app the carb entries are not shown anymore. In nightscout it is visible. Is that a known issue? Any suggestions? Thx

**Comment by jonfawcett** [comment]
There are a few issues you can check:
- nightscout url is correct? Easy to test... it is correct if the other NS data shows
- under debug or advanced menu, make sure the option to download and graph did not get turned off
- try restarting the app
- if none of these solve it, you most likely have an errant entry for carbs in NS. To prevent crashing the app, the code will skip items if it finds bad data in them. An example is a null value for carb grams. This usually only happens from 3 things: 1) you entered a decimal less than 1g and loop rounded to zero when uploading 2) loop had a glitch in the upload and all the data isn’t there 3) you manually created a “Meal Bolus” entry in NS
You have 2 options. 1) wait 24 hours after it started happening. The errant entry will be past the download window and no longer trigger the app to skip. 2) run a treatment report for the last 24 hours in NS and look at all the treatment entries for “Meal Bolus” to see if one lists no value or 0 for carbs or is missing other data. Delete it if you find it.

**Comment by rafaelsky** [comment]
Thanx, you are great. There was a meal entered without carbs!

**Comment by jonfawcett** [comment]
Glad it’s solved!
