### ISSUE TITLE
XCode opens into various targets causing my build to success, but no deployment

### ISSUE THREAD

**Issue by gregwaehner** [jonfawcett/LoopFollow#118]
Virtual Mac: BigSur 11.0.1
iphone: iphone SE (1st Gen) 14.2
XCode: 12.2

When I run the build script and XCode opens, I get a different target each time. I have to choose the "Loop Follow" active scheme rather than Eureka or Charts. If I don't change anything, I can choose my iphone, and build succeeds, but there is no deployment onto the iphone. Once I choose Loop Follow "active scheme" and sign my target, the build succeeds and deploys onto the phone.

**Comment by jonfawcett** [comment]
This is just an oddity in Xcode and nothing to do with Loop Follow code. To build any Xcode project to your phone, you must select the main project from the top (Loop Follow) and your phone next to it.

**Comment by gregwaehner** [comment]
Thanks Jon! Loving it already.
