### ISSUE TITLE
SAGE/CAGE

### ISSUE THREAD

**Issue by rafaelsky** [jonfawcett/LoopFollow#120]
Hi there. First of all: I love the App. Such a great work. Thank you.

In the Information Display there is a lkne for SAGE and CAGE, but I don't get the datas. How can I put the dates in there?

Thanx for help

**Comment by jonfawcett** [comment]
These are based on “CGM Sensor Start” (SAGE) and “Pump Site Change” (CAGE) in Nightscout. Each time you change sensor or cannula, use the + menu in NS to add this entry and then it will start displaying in Loop Follow

**Comment by rafaelsky** [comment]
Thank you so much for the help. I was looking for a FAQ, so I wouldn't need to bother you, but I couldn't find one.

Thanx

**Comment by jonfawcett** [comment]
https://www.youtube.com/watch?v=I7ay2lv9rF0
