### ISSUE TITLE
No such module 'Eureka'

### ISSUE THREAD

**Issue by Salasclan1** [jonfawcett/LoopFollow#125]
This error comes up during the build and then the Build Failed comes up.  The class is "AlarmViewController". I updated the iPhone to 14.4 but the error still comes up.  Please advise.

<img width="1080" alt="Screen Shot 2021-01-26 at 6 50 03 PM" src="https://user-images.githubusercontent.com/18433629/105926269-4f83b000-6007-11eb-80ef-1dd6c10eb432.png">
<img width="1080" alt="Screen Shot 2021-01-26 at 6 52 12 PM" src="https://user-images.githubusercontent.com/18433629/105926428-9b365980-6007-11eb-9055-f090268a86ca.png">

**Comment by jonfawcett** [comment]
You opened the project file instead of the workspace file.
