### ISSUE TITLE
SAGE always blank despite value being in NS

### ISSUE THREAD

**Issue by andrew-dixon** [jonfawcett/LoopFollow#128]
The SAGE value is always empty despite the option being enabled in NS and it displaying a value in NS. I've just recompiled on the latest "Main" branch and I'm still getting the same. Thinking about it now, I do not think I've ever seen a value in SAGE on the LoopFollow home screen.

![IMG_BFEECB31444F-1](https://user-images.githubusercontent.com/7441801/106397229-2c407280-6404-11eb-8061-6b2bc981acbd.jpeg)

![IMG_9E63933B829E-1](https://user-images.githubusercontent.com/7441801/106397232-31052680-6404-11eb-94cb-0568c4d6696e.jpeg)

**Comment by jonfawcett** [comment]
You are probably not using the correct sensor entry in NS. Sensor Start is used for when the sensor session starts and that is what drives SAGE in the app. Sensor Insert is used for insertion (not an active sensor session starting) which people use for tracking total sensor life if doing restarts. NS will use either to display the SAGE pill, but really it should have 2 separate pills for those.

**Comment by andrew-dixon** [comment]
@jonfawcett Not sure I agree with your analysis/implementation here. My understanding is "CGM Sensor Start" is for people who are "restarting" the CGM without replacing the sensor and "CGM Sensor Insert" is when you replace the sensor. As SAGE is "sensor age", then it should always show the "CGM Sensor Insert" unless this isn't defined and then it could fall back to "CGM Sensor Start" if that is defined. I think you have this the wrong way around TBH.

**Comment by dhermanns** [comment]
And this way it would be equal to the handling in nightguard.

**Comment by andrew-dixon** [comment]
I guess another way to handle it would be via a setting and allow the user to select which value they want to use.

**Comment by jonfawcett** [comment]
@andrew-dixon I don’t feel this is intuitive based on the naming of items in NS. Inserting a sensor has no bearing on when it expires. Starting a sensor is the only thing that triggers the cgm internal expiration timer. So that is why I have the alerts and sage based on Starting the sensor. Is there a reason you cannot use Sensor Start in careportal?

**Comment by andrew-dixon** [comment]
@jonfawcett No there is no reason I cannot use Sensor Start, it is just the way it is working is "wrong" 😬  and different from how others work. The "age" of the sensor is the time from when it was inserted, e.g. how long has it been on. As many people restart their sensors and use them multiple times, e.g. beyond the official 10-day life (Dexcom), I believe this is what it is meant to indicate, not necessarily how long the sensor has been running for since the most recent "start". I agree with your original analysis that these are really "different" things, but it appears that the "standard" interpretation for the SAGE value, is from insert, not start. 

I'll have a dig through the NS code for the SAGE pill and see what it is actually doing under-the-hood and report back.

**Comment by andrew-dixon** [comment]
I can confirm that this is not working as NS works. I've looked at both the code of NS and tried it with our most recent sensor change, by only updating the `CGM Start` and not the `CGM Insert` and NS didn't reset the SAGE pill but LoopFollow did as shown in this screenshots taken at the same time:

![IMG_0459](https://user-images.githubusercontent.com/7441801/107009316-c568e380-678c-11eb-86cc-3ca75615caec.jpg)
![IMG_0460](https://user-images.githubusercontent.com/7441801/107009318-c69a1080-678c-11eb-9ad6-3ffcb3489330.jpg)
