### ISSUE TITLE
Prebolus max time bug

### ISSUE THREAD

**Issue by mikebash** [jonfawcett/LoopFollow#140]
Small bug in the missed bolus alarm. When you click down to 1 minute you can no longer return to 5 or 10. It's now 6 or 11 from then on. https://user-images.githubusercontent.com/42122348/135283064-d54f3a33-fec0-4579-bfdb-5b00b3f948d5.MOV

**Comment by jonfawcett** [comment]
I just happened to be in the code fixing something else. This is now fixed in both branches.
