### ISSUE TITLE
Protect settings against accidental changes

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#146]
I just had to coach assistants at school to fix some settings in Loop Follow that had accidentally been altered (both BG units and the NS Token had been changed by accident somehow). It's also not the first time settings are changed by accident.

Would it be possible to secure the settings, or in some way make it less likely to accidentally change settings?

**Comment by jonfawcett** [comment]
Thanks for the idea. The latest dev and test flight have a show/hide toggle for those settings.
