### ISSUE TITLE
Worldwide Dexcom Issue

### ISSUE THREAD

**Issue by jonfawcett** [jonfawcett/LoopFollow#148]
Here is a temporary fix if you can help test. I am not able to test with both nightscout and OUS dexcom servers for all possible combinations.

Replace files with the ones in this zip and rebuild:

/LoopFollow/Extensions/ShareClientExtension.swift
/Pods/SjareClient/ShareClient.swift

[ShareUpdates.zip](https://github.com/jonfawcett/LoopFollow/files/7645160/ShareUpdates.zip)

**Comment by rafaelsky** [comment]
First of all: Thank you for your effort.
I installed the share clients. I don't see a difference. No arrow so far, and the numbers from dexcom are inserted a minute later than it used to before the issue came up.
Greetings

**Comment by jonfawcett** [comment]
This issue caused the dexcom download to fail entirely. Does LF show Dexcom as the Bg source above the reading? It is does, that means this is at least a step in the right direction.

please run a debug session and break at line 75 of nightscout.swift “if(err == null)”

let me know what result returns…and error or values. Please post a screenshot. And it values, expand some of them so I can see what is listed for trend.

**Comment by rafaelsky** [comment]
![image](https://user-images.githubusercontent.com/73534596/144571223-7b90c941-fb02-46e9-894f-95029260e337.png)

Did not see it in the first place. BG is from NS! :-/

**Comment by rafaelsky** [comment]
Sorry, how do I run a Debug?

**Comment by jonfawcett** [comment]
https://developer.apple.com/documentation/xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs

**Comment by rafaelsky** [comment]
![image](https://user-images.githubusercontent.com/73534596/144580603-d2edb167-e4e1-45d4-9a58-c274a590ba28.png)

Probably that is not what you were looking for.
Sorry, wanted to help, but obviously I have not enough knowledge. :-/

**Comment by GerhardFuehrer** [comment]
![IMG_33C97E60CDB1-1](https://user-images.githubusercontent.com/54687194/144582175-dec7d21f-9f0b-481f-b130-6a8ef86517ec.jpeg)
Thanks a lot, Jon. After replacing the 2 files and rebuilding (LF dev) it now reads from Dexcom again and shows the trend arrow!

**Comment by rafaelsky** [comment]
I don't know why, but now it works again... Did not change anything since my last post.
![image](https://user-images.githubusercontent.com/73534596/144582950-c80029b4-7e79-49b2-946a-f64fb2918945.png)

**Comment by Mia021** [comment]
I used it and trends on Loop Follow are back! Thank you! (NS still old symbol, Europe, Slovakia)

**Comment by jonfawcett** [comment]
This final fix is now incorporated
