### ISSUE TITLE
Update readme to include feature list and video

### ISSUE THREAD

**Issue by ngnrfsk** [jonfawcett/LoopFollow#23]
For ease of access by the non-FB community, would be great to update the readme to include the material listed on FB/Looped & the little video, e.g. 

**General feature list**
- scrollable/scalable graph display with standard Bg details plus Loop status, Loop Prediction, and the General NS Care portal info
- option to override DND and system volume for all alerts
- snoozes per alert, presnooze, edit existing snooze, and snooze all alert settings
- the standard Low/High, Urgent Low/High, and missed reading alerts. High will have a persistence option that’s still to do. Eg high for x minutes
- fast drop/rise alerts with BG limits. Eg. Trigger fast drop only when under a BG where it’s an issue
- sage/cage reminder alerts for x hours before change
- Not Looping with Bg limits. So you can trigger the alert only if under or over a BG range.
- calendar entries to use watch complication with BG, arrow, delta, cob, iob and minutes ago (if old reading)
- background silent audio to keep iOS from killing the app. It has a selectable refresh rate that should help reduce battery usage. This is why it can’t go in the App Store for just a simple download.

**New functionality under consideration**
- basal, carb, and insulin entries to the graph
- missed bolus alert
- watch app
- mmol support
- ability to pull from dex share for Bg. So it can automatically switch to dex BG display for those times when NS has delayed readings.

**Comment by jonfawcett** [comment]
completed
