### ISSUE TITLE
Speak BG readings

### ISSUE THREAD

**Issue by Darylkj** [jonfawcett/LoopFollow#27]
Thanks again Jon for everything you are doing!

In spike there is a feature that will read BGs out loud every 5 minutes. I find it useful for times I can’t or will forget to check my screen. If you were able to add this sometime in the distant future I think it would be a great addition! I’m willing to help in anyway I can although with no coding knowledge whatsoever I’m not sure what I can do.

**Comment by jonfawcett** [comment]
In dev branch now for testing

**Comment by jonfawcett** [comment]
Pushed to main branch
