### ISSUE TITLE
Choose snooze time when alarm is triggered. 

### ISSUE THREAD

**Issue by niclas72** [jonfawcett/LoopFollow#38]
One of the features of Spike I appreciate the most is how easy it is to choose different snooze time  for the alarms depending on the situation. Sometimes I for example want 20 min snooze to see if bg is raising from a low and sometimes maybe 1 hours to give bg time to come down from a high. 

Would be great if a user can choose the snooze time when the alarm is triggered.  

![image1](https://user-images.githubusercontent.com/56639449/85385295-6c707600-b542-11ea-8000-204d8ac523d3.png)
![image0](https://user-images.githubusercontent.com/56639449/85385305-6ed2d000-b542-11ea-8d3a-a6abe0fd4dc8.png)

**Comment by jonfawcett** [comment]
I added this request in the latest Dev commit be0edb1d2ec03ce682f7988b55640169e3c45102. The snooze button now displays the default snooze time under it with a +/- stepper to increment or decrease before clicking snooze.
