### ISSUE TITLE
Render scheduled Basal levels

### ISSUE THREAD

**Issue by niclas72** [jonfawcett/LoopFollow#39]
I think its quite a good feature to be able to see not only your current basal levels but also your scheduled basal levels in form of a dotted line. This is presented in Spike and NS and I have used it quite a lot to get a quick overview of how my sons basal levels have been the the latest 24 h compered to the scheduled. In spike you can set different colors for example green for when you are running your scheduled basal and yellow/red for when you are running higher/lower basals but this is a bit of an extra. 

This whole feature is of more use when not using autobolus branches.

**Comment by jonfawcett** [comment]
dotted line for scheduled basal is pushed to dev for testing

**Comment by naromero77** [comment]
I rebuilt, but I don't see the scheduled basal. FWIW, I am running an autobolus branch.

**Comment by jonfawcett** [comment]
Then you built master instead of dev

**Comment by naromero77** [comment]
my fault, I am on dev now and see the scheduled basal.

**Comment by jonfawcett** [comment]
I'm still having a few crashes from it. Hopefully can get it sorted soon. Just comment out line 741 like below if you experience them. I'm not sure if it's only code-related or something to do with specific data.

  // updateBasalScheduledGraph()
