### ISSUE TITLE
Feature request: get pump (Omnipod) and sensor (G6) start time from Loop or Dexcom app

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#49]
If technically possible,  it would be nice to get the time of pump/sensor start imported to the Loop Follow app. It is possible to do this manually in Nightscout/careportal, but we never remember to do so. Can of course check on the little loopers phone, but it would be convenient to get it to Loop Follow or  NS automatically.

**Comment by jonfawcett** [comment]
nothing uploads this information automatically to nightscout, so this isn't possible
