### ISSUE TITLE
24 h time

### ISSUE THREAD

**Issue by CaspianGeben** [jonfawcett/LoopFollow#52]
24 h time, military time or as most of the world call it, Time. 
I never got the hang of PM and AM and it makes my head hurt 😂

**Comment by jonfawcett** [comment]
This is an easy code change if you want to make it on your copy. Edit the ChartXValueFormatter section at the top of Chart.swift. You'll see "hh:mm". You can change this to 24 hour time by using capital H...  HH:mm.

**Comment by CaspianGeben** [comment]
Thanks!

**Comment by bjornoleh** [comment]
Im afraid there are more of us who would love to have 24h time :) When you find the time.. I might test the suggested edit, in the meantime.

**Comment by jonfawcett** [comment]
I just pushed this change to dev branch for testing.  The graph should now automatically use 24 hour time if your phone is set to that
