### ISSUE TITLE
Clicking on the BG dots while using mmol units displays values in mg/dL

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#60]
Clicking on the BG dots while using mmol units displays values in mg/dL. Dev from July 2 or thereabouts.

**Comment by hummelstrand** [comment]
![43F59B31-CB16-4BB3-BE63-6D85BE716450](https://user-images.githubusercontent.com/2979793/87596132-e504c580-c6ef-11ea-8cc8-a45cc38f70c6.png)
Can confirm this, today’s Dev branch shows the same thing.

**Comment by bjornoleh** [comment]
To add to the previous observation, also the Pred. Min-Max value is displayed in mg/dL units (Dev of today, 2020-07-19)

![image](https://user-images.githubusercontent.com/63544115/87871797-d9492580-c9b3-11ea-9491-15e0b23ca46a.png)

**Comment by jonfawcett** [comment]
@bjornoleh the Min/Max is fixed in dev. The graph text isn't related to the info table text, so in the future please keep items like this in a new issue.

**Comment by jonfawcett** [comment]
In testing and should be fixed in Dev within a few weeks.
