### ISSUE TITLE
Improve readability of Snoozer screen

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#61]
Improve readability  of Snoozer screen, especially for iPad in landscape orientation, for viewing at a distance (2+ meters)

Currently the time is tiny (system display, outside of LoopFollow), and the other values are too small as well. 

I would like to see time, BG, delta and time ago, and possibly the arrow (pretty much like today, but with improved readability at a distance).  When available, possibly also the forcast min-max and endpoint, like in the Loop pill in NS.

Add auto scale font size to maximise readability?

Also pleasse review font type selection for readability, a figure nine or six can look a lot like a figure eight at a distance in poor viewing conditions (at night, no glasses etc):
![image](https://user-images.githubusercontent.com/63544115/86542539-c09e3180-bf16-11ea-95ca-60468a8f9f7d.png)

NS looks like this, with better readability for BG readings in the classic view, and also in the new configurable clock view (both combined in the new Split screen option available in current NS Dev.
![image](https://user-images.githubusercontent.com/63544115/86542591-1e327e00-bf17-11ea-8f4b-33cdac7e6986.png)

Please see the new configurable clock view in Nightscout Dev for inspiration:

https://github.com/nightscout/cgm-remote-monitor/pull/5625

https://github.com/nightscout/cgm-remote-monitor/commit/3d6f488edab52eff2d8357997efcda1d6b5b28d8

https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md

**Comment by jonfawcett** [comment]
Giant BG display on the snoozer tab is coming to dev with my next push. The other items are more than Im going to get into right now.
