### ISSUE TITLE
NS unreachable notification

### ISSUE THREAD

**Issue by naromero77** [jonfawcett/LoopFollow#62]
This is with dev branch with commits through July 2.

Build worked fine for a couple of days, but now the Follow App will not display anything. If I look at the Debug log, it just shows "Download device status, Download BG, Download profile, ... Download: SAVE" and just repeats. There is no actual error message.

**Comment by jonfawcett** [comment]
Please post a screenshot of the debug log. After that, Turn off all of the debug graph settings, restart the app, and see if it displays BG. If it does, do this one by one with each setting until you find the one causing the issue. Let me know which one it is and then DM me your NS url to take a look at the data causing the issue

**Comment by naromero77** [comment]
Here is the screen shot. Will do the next steps later today.[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by naromero77** [comment]
OK, I figured out what the issue is and unfortunately it was quite embarrassing.

The URL somehow got changed from: 
``https://``
to
``httpss://``

Two instead of one `s`

While its impossible to idiot proof things, perhaps what is needed here is some type of URL check. I think almost every NS url must have `https://` OR maybe you there is an extra button to confirm when a URL is changed.

**Comment by jonfawcett** [comment]
Glad you solved it and that the app performed as expected - not displaying anything rather than crashing and requiring a rebuild.

I think the simplest solution is to show a notification that Nightscout is unreachable. That will solve not just your issue with the https text but also a typo in the url itself.

**Comment by marionbarker** [comment]
fixed with PR #195
