### ISSUE TITLE
App icon displays wrong bg

### ISSUE THREAD

**Issue by SanderRemote20** [jonfawcett/LoopFollow#64]
![A6A0BB56-B112-4B4D-9740-5EBB12168AE7](https://user-images.githubusercontent.com/63503509/86979969-e891cd00-c182-11ea-99d5-fbdc9e520a3d.jpeg)
Instead of displaying 8.5, the icon shows 85.

**Comment by jonfawcett** [comment]
Please read the announcements on the fb group and search the group before posting issues
