### ISSUE TITLE
Make statistics field optional to give more space to the BG curve? (iPhone, portrait orientation)

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#72]
Make statistics field optional to give more space to the BG curve? (iPhone, portrait orientation)

Settings toggle (on/off) or possibly a dedicated button to call up the statistics view? 

The stats are something I would have a quick look at perhaps once a day. At the moment it is grabbing too much real estate on iPhones, at the expense of readability of the BG curve.

There is also some optimization to be done for the upper right hand data field, please see photos below.

iPhone SE gen1
![image](https://user-images.githubusercontent.com/63544115/87871936-fcc0a000-c9b4-11ea-886a-b713f470b51a.png)

iPhone SE gen2
![image](https://user-images.githubusercontent.com/63544115/87871951-13ff8d80-c9b5-11ea-8ded-05517b5f663f.png)

iPad Air2 portrait
![image](https://user-images.githubusercontent.com/63544115/87872055-d9e2bb80-c9b5-11ea-93b0-9cc327cef974.png)

iPad Air2 landscape
![image](https://user-images.githubusercontent.com/63544115/87872024-a99b1d00-c9b5-11ea-8ada-fde6957033b6.png)

Loop Follow - Dev as of 2020-07-19

**Comment by jonfawcett** [comment]
Setting toggles added to Dev for stats and the small graph
