### ISSUE TITLE
Inconsistencies in mmol setting

### ISSUE THREAD

**Issue by VillumsNightscout** [jonfawcett/LoopFollow#78]
BG is shown in mg/dl on chart also when setting is mmol.

Std.dev. is mg/dl also when setting is mmol.

![image](https://user-images.githubusercontent.com/44088657/88154275-e1e56a00-cc06-11ea-9d0d-f5c43a891441.png)

**Comment by jonfawcett** [comment]
Please do not post issues before reviewing existing issues to see if it is already opened.

**Comment by VillumsNightscout** [comment]
My apologies, Jon. I simply missed #60.

You should expect large uptake in use. I advertise your effort where I can :D

Thanks for your effort!

Steffen

**Comment by jonfawcett** [comment]
😀👍
