### ISSUE TITLE
Persistent notifications: BG delta value is shown in mg/dl when mmol units are used.

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#83]
Persistent notifications: BG delta value is shown in mg/dl when mmol units are used.

![20200725_191644](https://user-images.githubusercontent.com/63544115/88462617-02365280-cead-11ea-8d35-7764d4b6fa68.jpg)

**Comment by bjornoleh** [comment]
This is a Dev build from about a week ago, with Dexcom support.

**Comment by jonfawcett** [comment]
Fixed in dev
