### ISSUE TITLE
Autobolus values can overlap

### ISSUE THREAD

**Issue by andrew-dixon** [jonfawcett/LoopFollow#86]
If you have a lot of small autobolus entries one after the other they can end up overlapping as shown below:

![IMG_64964EB31B0F-1](https://user-images.githubusercontent.com/7441801/89105652-dc63fd00-d41a-11ea-9a17-18e2b9b7fc2a.jpeg)

We have the same issue on Nightscout which was addressed by adding some options for the bolus output, see https://github.com/nightscout/cgm-remote-monitor/issues/5514

Looking at LoopFollow, maybe just removing the leading zero for these "micro" boluses would resolve the issue.

**Comment by jonfawcett** [comment]
I have this updated and will be pushing it to Dev in the next few weeks. It will strip leading and trailing zeroes from bolus dots
