### ISSUE TITLE
Background Task Location Option

### ISSUE THREAD

**Issue by jonfawcett** [jonfawcett/LoopFollow#9]
From using Spike, sometimes the silent audio still gets killed in the background. It might be worth adding a secondary option to use background location data to force it to be kept alive

**Comment by semophoto** [comment]
Is there a way to limit the background audio? Have it run periodically like a heartbeat? Ive been researching all day for a solution but i have don’t really understand swift. 
My battery life is suffering hard, and i really like Loop Follow features.

**Comment by bjorkert** [comment]
HI @semophoto, sorry, I have not found another or better way to do this. If you can manage without the alarms then background mode can be turned off.
