### ISSUE TITLE
Nightscout alarm cannot be silence after the initial snooze

### ISSUE THREAD

**Issue by naromero77** [jonfawcett/LoopFollow#96]
This happens often and I have not figure out what exactly triggers. Let me know describe what I think that I see.

Suppose you have audible alarms set-up in Nightscout (NS). The following works:
1. You have the Follow app open
2. NS alarm goes off
3. Switch to the NS tab and see the NS alarm is active (evidence by a Yellow/Red Highlight rectangle)
4. Silence the NS alarm from within the Follow App. 

However, if you NS alarm was previously active and then snoozed, and then the alarm goes off again, the NS alarm is shown without Yellow/Red Highlighted rectangle but the BG reading is still Yellow/Red. The NS alarm is going off -- but there is no way to silence it without quitting the Follow app. alltogether and restarting it.

**Comment by jonfawcett** [comment]
Disable NS alarms under the 3 line menu of NS on that tab of Loop Follow
