### ISSUE TITLE
Swift Compliler Error

### ISSUE THREAD

**Issue by jonamyhoze** [jonfawcett/LoopFollow#97]
After I build and put in my phone and push play I get an error of Swift Compiler Error and no such module Eureka?

I've watched the Youtube video and followed step by step.  I got stuck after pushing play.

**Comment by jonfawcett** [comment]
Please do not take this too harshly. I build this app and run the FB group out of my own spare time to help people. Please do not abuse my time by posting to both FB and Github before you have even searched for the solution yourself. A search of both of your keyword phrases 'compile error' or 'eureka' on FB show you the solution in several existing posts.
